sync docs with go reasons
kyma-project/btp-manager pull request #246
Opened 2023-03-28 13:10 UTC by ukff

- add small go program which validates if declarated reasons are in sync with their metadata, if no it generates new md table which dev need to copy and insert into md file.
- update pipeline to execute it as test

2023-03-30 10:31 UTC, IwonaLanger approved these changes

2023-03-31 12:02 UTC, IwonaLanger submitted a review, later dismissed

2023-04-04 11:41 UTC, jaroslaw-pieszka requested changes

2023-04-04 11:41 UTC, jaroslaw-pieszka commented on Makefile
> +	go run hack/autodoc/autodoc.go
We need to move it to other location. `hack` is kind of reserved. We could move it to `scripts` or create new directory.

2023-04-04 11:41 UTC, jaroslaw-pieszka commented on hack/autodoc/autodoc.go
> +	cmd := exec.Command("/bin/sh", "hack/autodoc/extract_conditions_data.sh")
extract script name (you use it in main in message) to make it easier to change.

2023-04-04 11:41 UTC, jaroslaw-pieszka commented on hack/autodoc/autodoc.go
> +	spaceMargin             = 10
Consider externalizing configuration (to allow adjusting without recompiling etc).

2023-04-04 11:41 UTC, jaroslaw-pieszka commented on hack/autodoc/autodoc.go
> +			errors = append(errors, fmt.Sprintf("there is a Reason = (%s) declarated in const scope, but there is no matching metadata for it", constReason))
```suggestion
			errors = append(errors, fmt.Sprintf("there is a Reason = (%s) declared in const scope, but there is no matching metadata for it", constReason))
```

2023-04-04 11:41 UTC, jaroslaw-pieszka commented on hack/autodoc/autodoc.go
> +		crState := cleanLine[1]
Here (and below) we risk accessing non-existing elements (if MD table is corrupted).

2023-04-04 11:41 UTC, jaroslaw-pieszka commented on hack/autodoc/autodoc.go
> +		element := ""
Why? To let you use `+=` in the next line?

2023-04-04 11:41 UTC, jaroslaw-pieszka commented on hack/autodoc/autodoc.go
> +	goLine = strings.Replace(goLine, "\n", "", -1)
Would strings.Trim suffice?

2023-04-04 11:41 UTC, jaroslaw-pieszka commented on hack/autodoc/autodoc.go
> +		return fmt.Errorf("goLine (%s) is bad structured, it should have following format (Reason: TypeAndStatus, //CRState;Remark", goLine), nil
```suggestion
		return fmt.Errorf("goLine (%s) is badly structured, it should have following format (Reason: TypeAndStatus, //CRState;Remark", goLine), nil
```

2023-04-04 11:41 UTC, jaroslaw-pieszka commented on hack/autodoc/autodoc.go
> +		return fmt.Errorf("comment in goLine (%s) is bad structured, it should have following format (//CRState;Remark)", goLine), nil
```suggestion
		return fmt.Errorf("comment in goLine (%s) is badly structured, it should have following format (//CRState;Remark)", goLine), nil
```

2023-04-04 12:12 UTC, MarekMichali commented on cmd/autodoc/main.go
> +}
In addition to the exit code, we could also add a log indicating that the script was executed correctly. Currently, if executed correctly, we get no information expect the code, and in the future someone who doesn't know the errorExitCode might wonder if it worked at all.

2023-04-04 12:26 UTC, jaroslaw-pieszka commented on hack/autodoc/autodoc.go
> +	spaceMargin             = 10
After discussion we decided to postpone this task to next MVP.

2023-04-04 12:26 UTC, jaroslaw-pieszka approved these changes

2023-04-04 12:30 UTC, IwonaLanger approved these changes

2023-04-04 12:32 UTC, merged