Testing OOM
kyma-project/btp-manager pull request #361
Opened 2023-07-25 09:18 UTC by piotrmiskiewicz

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2023-07-25 09:20 UTC, piotrmiskiewicz commented
/test all

2023-07-25 10:31 UTC, piotrmiskiewicz commented
/hold

2023-07-26 06:53 UTC, PK85 commented on controllers/cache.go
> +		&corev1.Secret{}:    objSelector,
Have you limited that to secrets and configmaps only by purpose? I mean we have webhooks too.

2023-07-26 07:00 UTC, PK85 requested changes
Add a new document about controller cache. Mention how we build cache and why

2023-07-26 07:58 UTC, piotrmiskiewicz commented on scripts/testing/create-secrets-configmaps.sh
> +#!/usr/bin/env bash
will be done in separate PR

2023-07-26 09:39 UTC, piotrmiskiewicz commented
/retest

2023-07-26 10:35 UTC, PK85 approved these changes

2023-07-26 11:05 UTC, piotrmiskiewicz commented
/unhold

2023-07-26 11:05 UTC, piotrmiskiewicz commented
/hold

2023-07-26 11:08 UTC, IwonaLanger commented on docs/contributor/07-10-informer-cache.md
> +The controller manager uses informers with a cache. All observed resources (btpoperator, secret, configmap etc.) are stored in the cache. Because of out of memory risk, the cache is configured with a
The phrase "the out of memory risk" should be changed to:
- the out-of-memory risk if 'out-of-memory' just describes the type of risk
- the "out of memory" risk if 'out of memory' is the name used for the risk

2023-07-26 11:08 UTC, IwonaLanger commented on scripts/testing/create-secrets-configmaps.sh
> +# Creates btp-operator and numerous service instances and service bindings in current context.
```suggestion
# Creates btp-operator and numerous Service Instances and Service Bindings in the current context.
```

2023-07-26 11:08 UTC, IwonaLanger commented on scripts/testing/create-secrets-configmaps.sh
> +#     - number of config maps and secrets (the provided number is multiplied by 10)
```suggestion
#     - number of Config Maps and Secrets (the provided number is multiplied by 10)
```

2023-07-26 11:31 UTC, IwonaLanger approved these changes

2023-07-26 11:35 UTC, piotrmiskiewicz commented
/unhold

2023-07-26 12:48 UTC, merged